import fs from 'fs';
import path from 'path';

export interface CheckResult {
  blocked: boolean;
  message?: string;
}

export function parseHookInput(input: string): string {
  try {
    const data = JSON.parse(input);
    return data.tool_input?.file_path || data.file_path || '';
  } catch {
    return '';
  }
}

export function checkGenerated(filePath: string): CheckResult {
  if (!filePath) {
    return { blocked: false };
  }

  const clayFilePath = path.resolve('.clay');
  if (!fs.existsSync(clayFilePath)) {
    return { blocked: false };
  }

  // Compute relative path; if it starts with ".." the file is outside the project
  const relPath = path.relative(path.resolve('.'), path.resolve(filePath));
  if (relPath.startsWith('..') || path.isAbsolute(relPath)) {
    return { blocked: false };
  }

  let clay;
  try {
    clay = JSON.parse(fs.readFileSync(clayFilePath, 'utf8'));
  } catch {
    return { blocked: false };
  }

  for (const model of clay.models || []) {
    if (relPath in (model.generated_files || {})) {
      const modelPath = model.path || 'unknown';
      return {
        blocked: true,
        message:
          `BLOCKED: ${relPath} is generated by Clay from model ${modelPath}.\n` +
          `\n` +
          `Do NOT edit this file directly. Instead, use the Clay MCP tools:\n` +
          `  1. clay_model_query - inspect the model at ${modelPath}\n` +
          `  2. clay_model_add / clay_model_update - modify the model\n` +
          `  3. clay_generate - regenerate all code from the model\n` +
          `\n` +
          `See https://morkeleb.github.io/clay/pages/mcp-server.html for details.`,
      };
    }
  }

  return { blocked: false };
}
