import fs from 'fs-extra';
import path from 'path';

const HOOK_SCRIPT = `#!/bin/bash
# Hook: Block Claude from editing Clay-generated files.
# Reads the tool input JSON from stdin to extract the file path,
# then checks if the file is listed in the .clay manifest.

set -euo pipefail

INPUT=$(cat)

# Extract file_path from the JSON input
FILE_PATH=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('file_path',''))" 2>/dev/null)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Find the project root (where .clay lives)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CLAY_FILE="$PROJECT_ROOT/.clay"

if [ ! -f "$CLAY_FILE" ]; then
  exit 0
fi

# Get relative path from project root
REL_PATH="\${FILE_PATH#$PROJECT_ROOT/}"

# If the path didn't change, the file isn't under the project root
if [ "$REL_PATH" = "$FILE_PATH" ]; then
  exit 0
fi

# Check if this relative path is in the .clay generated_files manifest
IS_GENERATED=$(python3 -c "
import json, sys
with open('$CLAY_FILE') as f:
    clay = json.load(f)
for model in clay.get('models', []):
    if '$REL_PATH' in model.get('generated_files', {}):
        print('yes')
        sys.exit(0)
print('no')
" 2>/dev/null)

if [ "$IS_GENERATED" = "yes" ]; then
  echo "BLOCKED: $REL_PATH is generated by Clay (listed in .clay manifest)."
  echo ""
  echo "Do NOT edit this file directly. Instead, use the Clay MCP tools:"
  echo "  1. clay_model_query - inspect current model structure"
  echo "  2. clay_model_add / clay_model_update - modify your model"
  echo "  3. clay_generate - regenerate all code from the model"
  echo ""
  echo "See https://morkeleb.github.io/clay/pages/mcp-server.html for details."
  exit 2
fi

exit 0
`;

const SETTINGS_HOOK = {
  matcher: 'Edit|Write',
  hooks: [
    {
      type: 'command',
      command: '.claude/hooks/check-generated-file.sh',
    },
  ],
};

export function initClaude(projectDir: string): void {
  const claudeDir = path.join(projectDir, '.claude');
  const hooksDir = path.join(claudeDir, 'hooks');
  const settingsPath = path.join(claudeDir, 'settings.json');
  const hookPath = path.join(hooksDir, 'check-generated-file.sh');

  // Ensure directories exist
  fs.mkdirSync(hooksDir, { recursive: true });

  // Write hook script
  fs.writeFileSync(hookPath, HOOK_SCRIPT, { mode: 0o755 });

  // Read or create settings.json, merging hooks
  let settings: Record<string, unknown> = {};
  if (fs.existsSync(settingsPath)) {
    settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
  }

  if (!settings.hooks) {
    settings.hooks = {};
  }
  const hooks = settings.hooks as Record<string, unknown[]>;

  if (!hooks.PreToolUse) {
    hooks.PreToolUse = [];
  }

  // Don't add duplicate
  const preToolUse = hooks.PreToolUse as Array<{ matcher?: string }>;
  const alreadyExists = preToolUse.some(
    (h) => h.matcher === 'Edit|Write'
  );

  if (!alreadyExists) {
    preToolUse.push(SETTINGS_HOOK);
  }

  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n');
}
